### ISSUE TITLE
Could not resolve artifact org.openapitools:openapi-generator:jar:sources

### ISSUE THREAD

**Issue by FernandoGarcia1995** [OAI/OpenAPI-Specification#3074]
I am trying to implement openapi plugin generator , but when i run `mvn clean install` I get the following error.

```
    org.eclipse.core.runtime.CoreException: Could not resolve artifact org.openapitools:openapi-generator:jar:sources:${openapi-generator-version}
    	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$4(MavenImpl.java:828)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:182)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:117)
    	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:103)
    	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:796)
    	at org.eclipse.m2e.core.internal.embedder.MavenImpl.resolve(MavenImpl.java:773)
```

Here is my pom.xml

```
    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    	<modelVersion>4.0.0</modelVersion>
    	<parent>
    		<groupId>org.springframework.boot</groupId>
    		<artifactId>spring-boot-starter-parent</artifactId>
    		<version>2.7.3</version>
    		<relativePath /> <!-- lookup parent from repository -->
    	</parent>
    	<groupId>com.company.project</groupId>
    	<artifactId>company</artifactId>
    	<version>0.0.1-SNAPSHOT</version>
    	<name>company</name>
    	<description>Demo project for Spring Boot</description>
    	<properties>
    		<java.version>8</java.version>
    	</properties>
    
    	<dependencies>
    		<dependency>
    			<groupId>org.springframework.boot</groupId>
    			<artifactId>spring-boot-starter-validation</artifactId>
    		</dependency>
    		<dependency>
    			<groupId>org.springframework.boot</groupId>
    			<artifactId>spring-boot-starter-web</artifactId>
    		</dependency>
    
    		<dependency>
    			<groupId>org.springframework.boot</groupId>
    			<artifactId>spring-boot-devtools</artifactId>
    			<scope>runtime</scope>
    			<optional>true</optional>
    		</dependency>
    
    		<dependency>
    			<groupId>org.springframework.boot</groupId>
    			<artifactId>spring-boot-starter-test</artifactId>
    			<scope>test</scope>
    		</dependency>
    
    		<dependency>
    			<groupId>org.openapitools</groupId>
    			<artifactId>openapi-generator</artifactId>
    			<version>6.2.0</version>
    		</dependency>
    
    	</dependencies>
    
    	<build>
    		<plugins>
    			<plugin>
    				<groupId>org.springframework.boot</groupId>
    				<artifactId>spring-boot-maven-plugin</artifactId>
    			</plugin>
    
    			<!--https://openapi-generator.tech/docs/plugins/-->
    			<plugin>
    				<groupId>org.openapitools</groupId>
    				<artifactId>openapi-generator-maven-plugin</artifactId>
    				<!-- RELEASE_VERSION -->
    				<version>5.1.0</version>
    				<!-- /RELEASE_VERSION -->
    				<executions>
    					<execution>
    						<goals>
    							<goal>generate</goal>
    						</goals>
    						<configuration>
    							<inputSpec>${project.basedir}/src/main/resources/test.yaml</inputSpec>
    							<output>${project.build.directory}/</output>
    							<generateSupportingFiles>true</generateSupportingFiles>
    							<generatorName>spring</generatorName>
    							<strictSpec>true</strictSpec>
    							<generateApiTests>false</generateApiTests>
    							<generateModelTests>false</generateModelTests>
    							<configOptions>
    								<controllerThrowsExceptions>java.io.IOException,com.example.NotFoundException</controllerThrowsExceptions>
    								<library>spring-mvc</library>
    								<interfaceOnly>true</interfaceOnly>
    								<skipDefaultInterface>true</skipDefaultInterface>
    								<useBeanValidation>true</useBeanValidation>
    								<useClassLevelBeanValidation>false</useClassLevelBeanValidation>
    								<useTags>true</useTags>
    								<java8>true</java8>
    								<useOptional>false</useOptional>
    								<hideGenerationTimestamp>true</hideGenerationTimestamp>
    								<dateLibrary>java8</dateLibrary>
    								<bigDecimalAsString>true</bigDecimalAsString>
    								<useBeanValidation>true</useBeanValidation>
    								<apiPackage>${codegen.api.package.name}</apiPackage>
    								<modelPackage>${codegen.model.page.name}</modelPackage>
    							</configOptions>
    						</configuration>
    					</execution>
    				</executions>
    			</plugin>
    		</plugins>
    	</build>
```

I have been looking at the documentation and it seems that the repository is on nexus ?

https://github.com/OpenAPITools/openapi-generator
https://search.maven.org/artifact/org.openapitools/openapi-generator

**Comment by rafalkrupinski** [comment]
You may want to ask this question in the appropriate repo. This one is about the specification

**Comment by FernandoGarcia1995** [comment]
> You may want to ask this question in the appropriate repo. This one is about the specification

correct, this issue could be removed.
