### ISSUE TITLE
Having issues with validating swagger.json file 

### ISSUE THREAD

**Issue by rameshappat** [OAI/OpenAPI-Specification#702]
Hello,
I have written a swagger.json file. The post operation contains two path parameters and one body parameter. the Body parameter type is defined in another JSON file and has other references etc.
I am trying to validate the file in the editor and keeps coming back with reference errors. Also I am trying to run this using Swagger UI and the body text box appears but the data type is not resolved to the correct complex type.

**Comment by wparad** [comment]
is #275 or [Reuse](https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/REUSE.md#remote-references) relevant?

**Comment by fehguy** [comment]
share your definition, please?

**Comment by fehguy** [comment]
Please reopen this in the swagger-js project, the resolution is implementation specific.

**Comment by rameshappat** [comment]
Here is the Swagger.json file.
It is hosted in a web server which has path of http://localhost:8080/dist/swagger.json<http://localhost:8080/dist/swagger.json>
The other external definition files are all in the dist directory


{
  "swagger": "2.0",
  "x-otm-resource": {
    "namespace": "http://www.travelport.com/schema/catalog/air/v0",
    "localName": "AirProduct"
  },
  "info": {
    "version": "1.0.0",
    "title": "ReservationResource API Specification"

  },
  "host": "localhost:8080",
  "basePath": "/",
  "schemes": [
    "http"
  ],

  "paths": {
    "/interactions/{interactionid}/reservation/{reservationid}": {
      "post": {
        "summary": "ReservationResource - Post",
        "operationId": "Post",
        "consumes":[
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/json",
          "application/xml"
        ],
        "parameters": [
          {
            "name": "interactionid",
            "in": "path",
            "description": "Interaction ID",
            "required": true,
            "type": "string"
          },
          {
            "name": "reservationid",
            "in": "path",
            "description": "Reservation ID",
            "required": true,
            "type": "string"
          },
          {
            "name": "reservation",
   "in": "body",
   "description": "reservation object",
            "required": true,
            "schema": {
               "$ref": "http://localhost:8080/dist/ReservationDomain_2_0_0.schema.json"
        }
          }
        ],
        "responses": {
          "200": {
            "description": "Retrieves a 1G Booking"
          }
        }
      }
    }
  }
}




________________________________

**Comment by rameshappat** [comment]
here is the swagger JSON file.
it is hosted in a webserver and the path is http://localhost:8080/dist/Swagger.jsonhttp://localhost:8080/dist/Swagger.json
All the definition files are in the dist directory.
What is the relative or actual path to use to reference my definition? is it relative to the location of Swagger file or the API paths?

{
  "swagger": "2.0",
  "x-otm-resource": {
    "namespace": "http://www.travelport.com/schema/catalog/air/v0",
    "localName": "AirProduct"
  },
  "info": {
    "version": "1.0.0",
    "title": "ReservationResource API Specification"

  },
  "host": "localhost:8080",
  "basePath": "/",
  "schemes": [
    "http"
  ],

  "paths": {
    "/interactions/{interactionid}/reservation/{reservationid}": {
      "post": {
        "summary": "ReservationResource - Post",
        "operationId": "Post",
        "consumes":[
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/json",
          "application/xml"
        ],
        "parameters": [
          {
            "name": "interactionid",
            "in": "path",
            "description": "Interaction ID",
            "required": true,
            "type": "string"
          },
          {
            "name": "reservationid",
            "in": "path",
            "description": "Reservation ID",
            "required": true,
            "type": "string"
          },
          {
            "name": "reservation",
   "in": "body",
   "description": "reservation object",
            "required": true,
            "schema": {
               "$ref": "http://localhost:8080/dist/ReservationDomain_2_0_0.schema.json"
        }
          }
        ],
        "responses": {
          "200": {
            "description": "Retrieves a 1G Booking"
          }
        }
      }
    }
  }
}
________________________________

**Comment by fehguy** [comment]
Please open the issue in swagger-parser and share the contents of this:

```
http://localhost:8080/dist/ReservationDomain_2_0_0.schema.json
```

as it's referenced in your definition.

**Comment by rameshappat** [comment]
The swagger instance comes back as Null as I tried to do a toString on the object.
But when I tried to parse swagger.json, it came back with the following exception:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.RuntimeException: An exception was thrown while trying to deserialize the contents of http://localhost:8080/dist/ReservationDomain_2_0_0.schema.json into type interface io.swagger.models.Model
       at io.swagger.parser.util.DeserializationUtils.deserialize(DeserializationUtils.java:54)
       at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:102)
       at io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:26)
       at io.swagger.parser.processors.ModelProcessor.processRefModel(ModelProcessor.java:92)
       at io.swagger.parser.processors.ModelProcessor.processModel(ModelProcessor.java:33)
       at io.swagger.parser.processors.ParameterProcessor.processParameters(ParameterProcessor.java:44)
       at io.swagger.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:26)
       at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:72)
       at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:40)
       at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
       at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:52)
       at Testing.main(Testing.java:9)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: <html><body><p>There are currently 0 running SoapUI MockServices</p><ul></ul></p></body></html>; line: 1, column: 2]
       at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1576)
       at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
       at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:462)
       at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1624)
       at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:689)
       at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3105)
       at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051)
       at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2161)
       at io.swagger.parser.util.DeserializationUtils.deserialize(DeserializationUtils.java:48)
       ... 11 more

**Comment by webron** [comment]
@rameshappat you've repeatedly been asked to open a ticket on the right repository. I have no choice but to lock this topic.
